# Generated by SmallHarness release workflow — do not edit by hand.
class SmallHarness < Formula
  desc "Terminal-based agent harness for running small LLMs on your Mac"
  homepage "https://github.com/GetSmallAI/SmallHarness"
  version "1.2.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v1.2.7/small-harness-v1.2.7-aarch64-apple-darwin.tar.gz"
      sha256 "fc6e83c8e12e4bcc73f456169aae2d8a1ee565ec6d62e589160bf4e43c74f92b"
    end
    on_intel do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v1.2.7/small-harness-v1.2.7-x86_64-apple-darwin.tar.gz"
      sha256 "5cd3d637cc6424b0a2ded67362055e6520dea3c3075a54386f8167ac7fa28ab1"
    end
  end

  def install
    bin.install "small-harness"
    doc.install Dir["README.md", "Quickstart.md", "LICENSE"]
    generate_completions_from_executable(bin/"small-harness", "completions")
  end

  test do
    assert_match "small-harness", shell_output("#{bin}/small-harness completions bash")
  end
end
