# Generated by SmallHarness release workflow — do not edit by hand.
class SmallHarness < Formula
  desc "Terminal-based agent harness for running small LLMs on your Mac"
  homepage "https://github.com/GetSmallAI/SmallHarness"
  version "0.4.13"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v0.4.13/small-harness-v0.4.13-aarch64-apple-darwin.tar.gz"
      sha256 "b47c35cae35b396d37121622c9d1ca171ec48464521148ca07ac63401f2ff869"
    end
    on_intel do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v0.4.13/small-harness-v0.4.13-x86_64-apple-darwin.tar.gz"
      sha256 "7f759453638bdf43911084c76795230727ca629f2db66a9e1e0e7a691f9926ff"
    end
  end

  def install
    bin.install "small-harness"
    doc.install Dir["README.md", "Quickstart.md", "LICENSE"]
    generate_completions_from_executable(bin/"small-harness", "completions")
  end

  test do
    assert_match "small-harness", shell_output("#{bin}/small-harness completions bash")
  end
end
