# Generated by SmallHarness release workflow — do not edit by hand.
class SmallHarness < Formula
  desc "Terminal-based agent harness for running small LLMs on your Mac"
  homepage "https://github.com/GetSmallAI/SmallHarness"
  version "1.0.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v1.0.2/small-harness-v1.0.2-aarch64-apple-darwin.tar.gz"
      sha256 "05bbf2d91f3a85999c9849c989c8cc17fa3a9872725004d12391e934959381fb"
    end
    on_intel do
      url "https://github.com/GetSmallAI/SmallHarness/releases/download/v1.0.2/small-harness-v1.0.2-x86_64-apple-darwin.tar.gz"
      sha256 "3d8c219ab0bac800b016f004c6043949094b61107db09e8a3c9e5ebceaae2d10"
    end
  end

  def install
    bin.install "small-harness"
    doc.install Dir["README.md", "Quickstart.md", "LICENSE"]
    generate_completions_from_executable(bin/"small-harness", "completions")
  end

  test do
    assert_match "small-harness", shell_output("#{bin}/small-harness completions bash")
  end
end
